export const defaultButtons = [
  { id: '1', label: '7', type: 'text' },
  { id: '2', label: '8', type: 'text' },
  { id: '3', label: '9', type: 'text' },
  { id: '4', label: 'C', type: 'text' },
  { id: '5', label: '4', type: 'text' },
  { id: '6', label: '5', type: 'text' },
  { id: '7', label: '6', type: 'text' },
  {
    id: '8',
    label: 'erase',
    type: 'icon',
    iconLib: 'Entypo',
    iconName: 'erase',
  },
  { id: '9', label: '1', type: 'text' },
  { id: '10', label: '2', type: 'text' },
  { id: '11', label: '3', type: 'text' },
  { id: '12', label: '=', type: 'text' },
  { id: '13', label: '00', type: 'text' },
  { id: '14', label: '0', type: 'text' },
  { id: '15', label: '.', type: 'text' },
];
