export const currencyOptions = [
  { id: '1', label: 'Algerian Dinar DZD', value: 'DZD' },
  { id: '2', label: 'Argentine Peso ARS', value: 'ARS' },
  { id: '3', label: 'Australian Dollar AUD', value: 'AUD' },
  { id: '4', label: 'Bahrain Dinar BHD', value: 'BHD' },
  { id: '5', label: 'Bangladeshi Taka BDT', value: 'BDT' },
  { id: '6', label: 'Belarus Ruble BYN', value: 'BYN' },
  { id: '7', label: 'Brazilian Real BRL', value: 'BRL' },
  { id: '8', label: 'Brunei Ringgit BND', value: 'BND' },
  { id: '9', label: 'Bulgarian Lev BGN', value: 'BGN' },
  { id: '10', label: 'Burmese Kyat MMK', value: 'MMK' },
  { id: '11', label: 'Cambodian Riel KHR', value: 'KHR' },
  { id: '12', label: 'Canadian Dollar CAD', value: 'CAD' },
  { id: '13', label: 'Chilean Peso CLP', value: 'CLP' },
  { id: '14', label: 'Chinese Yuan CNY', value: 'CNY' },
  { id: '15', label: 'Colombian Peso COP', value: 'COP' },
  { id: '16', label: 'Costa Rican Colon CRC', value: 'CRC' },
  { id: '17', label: 'Czech Crown CZK', value: 'CZK' },
  { id: '18', label: 'Danish Krone DKK', value: 'DKK' },
  { id: '19', label: 'Egyptian Pound EGP', value: 'EGP' },
  { id: '20', label: 'Euro EUR', value: 'EUR' },
  { id: '21', label: 'Hong Kong Dollar HKD', value: 'HKD' },
  { id: '22', label: 'Hungarian Forint HUF', value: 'HUF' },
  { id: '23', label: 'Icelandic Krona ISK', value: 'ISK' },
  { id: '24', label: 'Indian Rupee INR', value: 'INR' },
  { id: '25', label: 'Indonesian Rupiah IDR', value: 'IDR' },
  { id: '26', label: 'Iranian Rial IRR', value: 'IRR' },
  { id: '27', label: 'Iraqi Dinar IQD', value: 'IQD' },
  { id: '28', label: 'Israel New Shekel ILS', value: 'ILS' },
  { id: '29', label: 'Japanese Yen JPY', value: 'JPY' },
  { id: '30', label: 'Jordanian Dinar JOD', value: 'JOD' },
  { id: '31', label: 'Kazakh Tenge KZT', value: 'KZT' },
  { id: '32', label: 'Kenya Shilling KES', value: 'KES' },
  { id: '33', label: 'Kuwait Dinar KWD', value: 'KWD' },
  { id: '34', label: 'Lao Kip LAK', value: 'LAK' },
  { id: '35', label: 'Lebanese Pound LBP', value: 'LBP' },
  { id: '36', label: 'Macanese Pataca MOP', value: 'MOP' },
  { id: '37', label: 'Malaysian Ringgit MYR', value: 'MYR' },
  { id: '38', label: 'Mexico Peso MXN', value: 'MXN' },
  { id: '39', label: 'Moldovan Leu MDL', value: 'MDL' },
  { id: '40', label: 'Morroccan Dirham MAD', value: 'MAD' },
  { id: '41', label: 'Naira NGN', value: 'NGN' },
  { id: '42', label: 'Nepalese Rupee NPR', value: 'NPR' },
  { id: '43', label: 'New Taiwan Dollar TWD', value: 'TWD' },
  { id: '44', label: 'New Zealand Dollar NZD', value: 'NZD' },
  { id: '45', label: 'Norwegian Krone NOK', value: 'NOK' },
  { id: '46', label: 'Omani Rial OMR', value: 'OMR' },
  { id: '47', label: 'Pakistan Rupee PKR', value: 'PKR' },
  { id: '48', label: 'Philippine Peso PHP', value: 'PHP' },
  { id: '49', label: 'Polish Zloty PLN', value: 'PLN' },
  { id: '50', label: 'Pound Sterling GBP', value: 'GBP' },
  { id: '51', label: 'Qatari Riyal QAR', value: 'QAR' },
  { id: '52', label: 'Romanian Leu RON', value: 'RON' },
  { id: '53', label: 'Russian Ruble RUB', value: 'RUB' },
  { id: '54', label: 'Saudi Riyal SAR', value: 'SAR' },
  { id: '55', label: 'Singapore Dollar SGD', value: 'SGD' },
  { id: '56', label: 'South African Rand ZAR', value: 'ZAR' },
  { id: '57', label: 'Sri Lanka Rupee LKR', value: 'LKR' },
  { id: '58', label: 'Swedish Krona SEK', value: 'SEK' },
  { id: '59', label: 'Swiss Franc CHF', value: 'CHF' },
  { id: '60', label: 'Syrian Pound SYP', value: 'SYP' },
  { id: '61', label: 'Tanzania Shilling TZS', value: 'TZS' },
  { id: '62', label: 'Thai Baht THB', value: 'THB' },
  { id: '63', label: 'Tunisian Dinar TND', value: 'TND' },
  { id: '64', label: 'Turkish Lira TRY', value: 'TRY' },
  { id: '65', label: 'UAE Dirham AED', value: 'AED' },
  { id: '66', label: 'Uganda Shilling UGX', value: 'UGX' },
  { id: '67', label: 'Ukranian Hryvna UAH', value: 'UAH' },
  { id: '68', label: 'US Dollar USD', value: 'USD' },
  { id: '69', label: 'Uzbekistani Som UZS', value: 'UZS' },
  { id: '70', label: 'Viet-namese Dong VND', value: 'VND' },
  { id: '71', label: 'Won KRW', value: 'KRW' },
  { id: '72', label: 'Zambian Kwacha ZMW', value: 'ZMW' },
];
